sudo: false
language: node_js
node_js:
  - '5'
cache:
  directories:
    - node_modules
    - bower_components
before_install:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'phantomjs --version'
  - 'firefox --version'
  - 'chromium-browser --version'
before_script:
  - 'npm install -g grunt-cli'
  - 'npm install -g karma-cli'
  - 'npm install -g webpack'
  - 'npm install'
script:
  - 'npm run test-browser'
  - 'npm run build'
after_success:
  - 'npm run coverage'
  - 'npm run coveralls'
